### ISSUE TITLE
link for the trained model

### ISSUE THREAD

**Issue by jiayily** [Chenyang-Lu/mono-semantic-occupancy#2]
Hi, link in the checkpoint folder seems not accessible. Could you please share another one?

**Comment by jiayily** [comment]
Make it after several times. Thank you.

**Comment by jiayily** [comment]
Each time when it is to complete, the downloading is forbidden.
![image](https://user-images.githubusercontent.com/16137282/121628321-8be21500-caab-11eb-942a-6941cba953cf.png)

**Comment by Chenyang-Lu** [comment]
Hi Jiayi719, 

It seems that I can still download it from the dropbox. But maybe you can try this link from onedrive, to see if it works.
https://1drv.ms/u/s!AthJr3PSm53WhN41CzRe0jYAZa7aPg?e=eaAWkM

Best,
Chenyang

**Comment by jiayily** [comment]
Thank you. It works.
