### ISSUE TITLE
How long does it take to train the model?

### ISSUE THREAD

**Issue by Yiir-1** [Chenyang-Lu/mono-semantic-occupancy#4]
Hello！Thanks for your good work ! Could you please explain what GPU you used to train models, and how long does it take?

**Comment by Chenyang-Lu** [comment]
Hi, 

I used a single Titan V. This work was done a few years ago so I cannot precisely remember the training time.
But I guess it takes less than 12 hours.

Best,
Chenyang

**Comment by Yiir-1** [comment]
Thanks for you reply！
